### ISSUE TITLE
Prevent direct commits to main

### ISSUE THREAD

**Issue by funnelfiasco** [guacsec/guac-landing#114]
Not for the first time, I've accidentally pushed changes directly to main. This isn't the worst thing that could happen, but it would be better if we prevented it.

I don't have the necessary settings access, so I'll ask someone else to do it.

**Comment by pxp928** [comment]
Branch protection enabled for main:

```
When enabled, all commits must be made to a non-protected branch and submitted via a pull request before they can be merged into a branch that matches this rule.
```

**Comment by pxp928** [comment]
closed as completed.
